version: "3.9"

services:
  django-server:
    image: 192.168.8.129:8101/django-server
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client:/usr/share/nginx/html
    ports:
      - "5140:5140"
    depends_on:
      - django-server
