# Generated by Django 5.2.1 on 2025-05-22 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('pesel', models.IntegerField()),
                ('data_urodzenia', models.DateField()),
                ('data_zatrudnienia', models.DateField()),
                ('data_modyfikacji', models.DateField()),
                ('data_utworzenia', models.DateField()),
                ('stanowisko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stanowisko', to='persons.job')),
            ],
        ),
    ]
