version: "3.8"

services:
  appmqtt:
    image: 192.168.8.129:8101/appmqtt
    volumes:
      - appmqtt_config:/app/config/
      - appmqtt_data:/app/data/
    ports:
      - "5555:5000"
    restart: always
volumes:
  appmqtt_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/config/
  appmqtt_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/data/
